config/routes.rb
Oksales::Application.routes.draw do
  resources :units

  root 'home#index'

  resources :clients do
    member do
      patch :confirm_update
    end

    collection do
      post :confirm_create
    end
  end

  resources :products do
    member do
      patch :confirm_update
    end

    collection do
      post :confirm_create
    end
  end

  resources :supplires do
    member do
      patch :confirm_update
    end

    collection do
      post :confirm_create
    end
  end

end

app/models/supplire.rb
require 'kconv'

class Supplire < ActiveRecord::Base
  before_validation :to_utf8

  validates :code, presence: true, length: { maximum: 5 }
  validates :name, presence: true, length: { maximum: 255 }
  validates :kana, length: { maximum: 255 }

  scope :matches, ->(supplire_search_form) {
    supplire_search_form.add_scopes(all)
  }

  private

  def to_utf8
    # NOTE: Kconv#toutf8(str) は半角カタカナを全角カタカナにします
    self.code = Kconv.toutf8(code) if code.present?
    self.name = Kconv.toutf8(name) if name.present?
    self.kana = Kconv.toutf8(kana) if kana.present?
  end
end

app/controllers/supplires_controller.rb
class SuppliresController < ApplicationController
  before_action :set_supplire, only: [:show, :edit, :confirm_update, :update, :destroy]

  # GET /supplires
  # GET /supplires.json
  def index
    @supplire_search_form = SupplireSearchForm.new(supplire_search_form_params)
    @supplires = Supplire.matches(@supplire_search_form)
  end

  # GET /supplires/1
  # GET /supplires/1.json
  def show
  end

  # GET /supplires/new
  def new
    @supplire = Supplire.new
  end

  def confirm_create
    @supplire = Supplire.new(supplire_params)

    respond_to do |format|
      if @supplire.valid?
        format.html { render }
      else
        format.html { render action: 'new' }
      end
    end
  end

  # GET /supplires/1/edit
  def edit
  end

  def confirm_update
    @supplire.attributes = supplire_params

    respond_to do |format|
      if @supplire.valid?
        format.html { render }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  # POST /supplires
  # POST /supplires.json
  def create
    @supplire = Supplire.new(supplire_params)

    respond_to do |format|
      if @supplire.save
        format.html { redirect_to @supplire, notice: t("message.successfully_created", name: Supplire.model_name.human) }
        format.json { render action: 'show', status: :created, location: @supplire }
      else
        format.html { render action: 'new' }
        format.json { render json: @supplire.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /supplires/1
  # PATCH/PUT /supplires/1.json
  def update
    @supplire.attributes = supplire_params

    respond_to do |format|
      if @supplire.save
        format.html { redirect_to @supplire, notice: t("message.successfully_updated", name: Supplire.model_name.human) }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @supplire.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /supplires/1
  # DELETE /supplires/1.json
  def destroy
    # NOTE: scaffold でつくられるコントローラでは destroy が使われていますが、
    #       戻り値を使わないのであれば、destroy! を使う方がより適切なので変えています。
    @supplire.destroy!
    respond_to do |format|
      format.html { redirect_to supplires_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_supplire
      @supplire = Supplire.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def supplire_params
      params.require(:supplire).permit(:code, :name, :short_name, :kana, :supplire_group_id, :price, :cost_price, :tax_type, :tax_class_id, :district, :supplire_id, :unit_id, :qty_per_box, :price_type, :item_of_matrixlist, :valid_from, :valid_until, :create_user_id, :update_user_id)
    end

    def supplire_search_form_params
      params.fetch(:supplire_search_form, {}).permit(:code, :name, :kana)
    end
end

app/helpers/supplires_helper.rb
module SuppliresHelper
end

app/views/supplires/_confirm.html.haml
.col-sm-12
  .box
    .box-header.blue-background
      .title 仕入先情報
    .box-content.box-padding
      .row
        .col-sm-3.item-name
          %p
            %b= Supplire.human_attribute_name :code
        .col-sm-9
          = @supplire.code
      .row
        .col-sm-3.item-name
          %p
            %b= Supplire.human_attribute_name :name
        .col-sm-9
          = @supplire.name
      .row
        .col-sm-3.item-name
          %p
            %b= Supplire.human_attribute_name :short_name
        .col-sm-9
          = @supplire.short_name
      .row
        .col-sm-3.item-name
          %p
            %b= Supplire.human_attribute_name :kana
        .col-sm-9
          = @supplire.kana
      .row
        .col-sm-3.item-name
          %p
            %b= Supplire.human_attribute_name :postal_code
        .col-sm-9
          = @supplire.postal_code
      .row
        .col-sm-3.item-name
          %p
            %b= Supplire.human_attribute_name :address1
        .col-sm-9
          = @supplire.address1
      .row
        .col-sm-3.item-name
          %p
            %b= Supplire.human_attribute_name :address2
        .col-sm-9
          = @supplire.address2
      .row
        .col-sm-3.item-name
          %p
            %b= Supplire.human_attribute_name :address3
        .col-sm-9
          = @supplire.address3
      .row
        .col-sm-3.item-name
          %p
            %b= Supplire.human_attribute_name :tel
        .col-sm-9
          = @supplire.tel
      .row
        .col-sm-3.item-name
          %p
            %b= Supplire.human_attribute_name :fax
        .col-sm-9
          = @supplire.fax
      .row
        .col-sm-3.item-name
          %p
            %b= Supplire.human_attribute_name :url
        .col-sm-9
          = @supplire.url
      .row
        .col-sm-3.item-name
          %p
            %b= Supplire.human_attribute_name :pic_name
        .col-sm-9
          = @supplire.pic_name
      .row
        .col-sm-3.item-name
          %p
            %b= Supplire.human_attribute_name :pic_email
        .col-sm-9
          = @supplire.pic_email

  = form_for @supplire, html: {class: 'form-horizontal', role: 'form'} do |f|
    - %i|code name short_name kana postal_code address1 address2 address3 fax url pic_name pic_email price_ratio|.each do |column|
      = f.hidden_field column

    .form-actions
      .row
        .col-sm-8.col-sm-offset-3
          = f.submit '保存', class: 'btn btn-primary'
          = link_to '戻る', @supplire.new_record? ? new_supplire_path : edit_supplire_path, class: 'btn', onclick: "window.history.back();"

app/views/supplires/_form.html.haml
= form_for @supplire, url: @supplire.new_record? ? confirm_create_supplires_path : confirm_update_supplire_path, html: {class: 'form-horizontal', role: 'form'} do |f|
  - if @supplire.errors.any?
    #error_explanation.alert.alert-danger
      %ul
        - @supplire.errors.full_messages.each do |msg|
          %li= msg
  .box
    .box-header.blue-background
      .title 仕入先情報
    .box-content.box-padding
      .form-group
        = f.label :code, class: 'control-label col-sm-3' do
          = Supplire.human_attribute_name :code
          %span.required_mark *
        .col-sm-8
          = f.text_field :code, class: 'form-control'
      
      .form-group
        = f.label :name, class: 'control-label col-sm-3' do
          = Supplire.human_attribute_name :name
          %span.required_mark *
        .col-sm-8
          = f.text_field :name, class: 'form-control'

      .form-group
        = f.label :short_name, class: 'control-label col-sm-3'
        .col-sm-8
          = f.text_field :short_name, class: 'form-control'

      .form-group
        = f.label :kana, class: 'control-label col-sm-3'
        .col-sm-8
          = f.text_field :kana, class: 'form-control'

      .form-group
        = f.label :postal_code, class: 'control-label col-sm-3'
        .col-sm-8
          = f.text_field :postal_code, class: 'form-control'

      .form-group
        = f.label :address1, class: 'control-label col-sm-3'
        .col-sm-8
          = f.text_field :address1, class: 'form-control'

      .form-group
        = f.label :address2, class: 'control-label col-sm-3'
        .col-sm-8
          = f.text_field :address2, class: 'form-control'

      .form-group
        = f.label :address3, class: 'control-label col-sm-3'
        .col-sm-8
          = f.text_field :address3, class: 'form-control'

      .form-group
        = f.label :tel, class: 'control-label col-sm-3'
        .col-sm-8
          = f.text_field :tel, class: 'form-control'

      .form-group
        = f.label :fax, class: 'control-label col-sm-3'
        .col-sm-8
          = f.text_field :fax, class: 'form-control'

      .form-group
        = f.label :url, class: 'control-label col-sm-3'
        .col-sm-8
          = f.text_field :url, class: 'form-control'

      .form-group
        = f.label :pic_name, class: 'control-label col-sm-3'
        .col-sm-8
          = f.text_field :pic_name, class: 'form-control'

      .form-group
        = f.label :pic_email, class: 'control-label col-sm-3'
        .col-sm-8
          = f.text_field :pic_email, class: 'form-control'

      .form-group
        = f.label :price_ratio, class: 'control-label col-sm-3'
        .col-sm-8
          = f.number_field :price_ratio, class: 'form-control'

    .form-actions
      .row
        .col-sm-8.col-sm-offset-3
          = f.submit '確認', class: 'btn btn-primary'
          = link_to '戻る', supplires_path, class: 'btn btn-defalut'

app/views/supplires/confirm_create.html.haml
- content_for :title do
  新しい仕入先を登録（確認）

- content_for :breadcrumb do
  %li
    =link_to :root do
      ホーム
  %li.separator
    %i.icon-angle-right
  %li
    =link_to supplires_path do
      仕入先情報
  %li.separator
    %i.icon-angle-right
  %li.active
    新しい仕入先を登録（確認）

= render 'confirm'

app/views/supplires/confirm_update.html.haml
- content_for :title do
  仕入先を編集（確認）

- content_for :breadcrumb do
  %li
    =link_to :root do
      ホーム
  %li.separator
    %i.icon-angle-right
  %li
    =link_to supplires_path do
      仕入先情報
  %li.separator
    %i.icon-angle-right
  %li.active
    仕入先を編集（確認）

= render 'confirm'

app/views/supplires/edit.html.haml
- content_for :title do
  仕入先を編集

- content_for :breadcrumb do
  %li
    =link_to :root do
      ホーム
  %li.separator
    %i.icon-angle-right
  %li
    =link_to supplire_path do
      仕入先情報
  %li.separator
    %i.icon-angle-right
  %li.active
    仕入先を編集

.col-sm-12
  = render 'form'

app/views/supplires/index.html.haml
- content_for :title do
  仕入先情報

- content_for :breadcrumb do
  %li
    =link_to :root do
      ホーム
  %li.separator
    %i.icon-angle-right
  %li.active
    仕入先情報

.col-sm-12
  .box
    .box-content.box-padding
      = form_for @supplire_search_form, url: supplires_path, html: {method: :get, role: 'form'} do |f|
        .row
          .col-sm-2
            .form-group
              = f.label :code, class: 'control-label'
              = f.text_field :code, class: 'form-control'
          .col-sm-4
            .form-group
              = f.label :name, class: 'control-label'
              = f.text_field :name, class: 'form-control'
          .col-sm-4
            .form-group
              = f.label :kana, class: 'control-label'
              = f.text_field :kana, class: 'form-control'
        .row
          .col-sm-12
            = button_tag type: 'submit', class: 'btn' do
              <i class="icon-search"></i>検索

.col-sm-12
  .box
    .box-content.box-padding
      = link_to '<i class="icon-plus"></i>新しい仕入先を登録'.html_safe, new_supplire_path, class: 'btn'

.col-sm-12
  .box
    .box-content.box-no-padding{style: 'border:none;'}
      .box.bordered-box.blue-border{style: "margin-bottom:0;"}
        .box-header.blue-background
          .title 仕入先一覧
      %table.table.table-bordered
        %tr
          %th.col-sm-1= Supplire.human_attribute_name :code
          %th.col-sm-3= Supplire.human_attribute_name :name
          %th.col-sm-1 詳細
          %th.col-sm-1 編集
          %th.col-sm-1 削除

        - @supplires.each do |supplire|
          %tr
            %td= supplire.code
            %td= supplire.name
            %td
              =link_to supplire_path(supplire) do
                %i.icon-large.icon-file"
            %td
              = link_to edit_supplire_path(supplire) do
                %i.icon-large.icon-edit
            %td
              = link_to supplire, :method => :delete, :data => { :confirm => t('message.delete_confirm') } do
                %i.icon-large.icon-trash

app/views/supplires/new.html.haml
- content_for :title do
  新しい仕入先を登録

- content_for :breadcrumb do
  %li
    =link_to :root do
      ホーム
  %li.separator
    %i.icon-angle-right
  %li
    =link_to supplires_path do
      仕入先情報
  %li.separator
    %i.icon-angle-right
  %li.active
    新しい仕入先を登録

.col-sm-12
  = render 'form'

app/views/supplires/show.html.haml
- content_for :title do
  仕入先詳細

- content_for :breadcrumb do
  %li
    =link_to :root do
      ホーム
  %li.separator
    %i.icon-angle-right
  %li
    =link_to supplires_path do
      仕入先情報
  %li.separator
    %i.icon-angle-right
  %li.active
    仕入先詳細

- if notice
  .col-sm-12
    %p#notice.alert.alert-info= notice

.col-sm-12
  .box
    .box-header.blue-background
      .title 仕入先情報
    .box-content.box-padding
      .row
        .col-sm-3.item-name
          %p
            %b= Supplire.human_attribute_name :code
        .col-sm-9
          = @supplire.code
      .row
        .col-sm-3.item-name
          %p
            %b= Supplire.human_attribute_name :name
        .col-sm-9
          = @supplire.name
      .row
        .col-sm-3.item-name
          %p
            %b= Supplire.human_attribute_name :short_name
        .col-sm-9
          = @supplire.short_name
      .row
        .col-sm-3.item-name
          %p
            %b= Supplire.human_attribute_name :kana
        .col-sm-9
          = @supplire.kana
      .row
        .col-sm-3.item-name
          %p
            %b= Supplire.human_attribute_name :postal_code
        .col-sm-9
          = @supplire.postal_code
      .row
        .col-sm-3.item-name
          %p
            %b= Supplire.human_attribute_name :address1
        .col-sm-9
          = @supplire.address1
      .row
        .col-sm-3.item-name
          %p
            %b= Supplire.human_attribute_name :address2
        .col-sm-9
          = @supplire.address2
      .row
        .col-sm-3.item-name
          %p
            %b= Supplire.human_attribute_name :address3
        .col-sm-9
          = @supplire.address3
      .row
        .col-sm-3.item-name
          %p
            %b= Supplire.human_attribute_name :tel
        .col-sm-9
          = @supplire.tel
      .row
        .col-sm-3.item-name
          %p
            %b= Supplire.human_attribute_name :fax
        .col-sm-9
          = @supplire.fax
      .row
        .col-sm-3.item-name
          %p
            %b= Supplire.human_attribute_name :url
        .col-sm-9
          = @supplire.url
      .row
        .col-sm-3.item-name
          %p
            %b= Supplire.human_attribute_name :pic_name
        .col-sm-9
          = @supplire.pic_name
      .row
        .col-sm-3.item-name
          %p
            %b= Supplire.human_attribute_name :pic_email
        .col-sm-9
          = @supplire.pic_email
      .row
        .col-sm-3.item-name
          %p
            %b= Supplire.human_attribute_name :price_ratio
        .col-sm-9
          = @supplire.price_ratio
      .row
        .col-sm-3.item-name
          %p
            %b= Supplire.human_attribute_name :created_at
        .col-sm-9
          = l @supplire.created_at
      .row
        .col-sm-3.item-name
          %p
            %b= Supplire.human_attribute_name :updated_at
        .col-sm-9
          = l @supplire.updated_at

.col-sm-12
  .form-actions
    .row
      .col-sm-8.col-sm-offset-2
        = link_to '編集', edit_supplire_path(@supplire), class: 'btn btn-primary'
        = link_to '戻る', supplires_path, class: 'btn'