config/routes.rb
Oksales::Application.routes.draw do
  resources :units

  root 'home#index'

  resources :clients do
    member do
      patch :confirm_update
    end

    collection do
      post :confirm_create
    end
  end

  resources :products do
    member do
      patch :confirm_update
    end

    collection do
      post :confirm_create
    end
  end

  resources :supplires do
    member do
      patch :confirm_update
    end

    collection do
      post :confirm_create
    end
  end

end

app/models/client.rb
require 'kconv'

class Client < ActiveRecord::Base
  before_validation :to_utf8

  validates :name, presence: true, length: { maximum: 255 }
  validates :abbr, length: { maximum: 255 }
  validates :code, length: { maximum: 255 }, uniqueness: true, allow_blank: true
  validates :full_name, length: { maximum: 255 }
  validates :full_name_kana, length: { maximum: 255 }, format: {with: /\A[\p{katakana}ー－]+\z/, message: :invalid_katakana_format}, allow_blank: true
  validates :zipcode, format: { with: /\A[0-9]{7}\z/, message: :invalid_zipcode_format }, allow_blank: true
  validates :pref_name, length: { maximum: 255 }
  validates :address_city, length: { maximum: 255 }
  validates :address_extra, length: { maximum: 255 }
  validates :sales_person_name, length: { maximum: 255 }
  validates :sales_person_email, length: { maximum: 255 }, allow_blank: true,
    # NOTE: サンプルのため、チェックをゆるめにしています。
    #       厳密なチェックが必要な場合は gem を使うのがおすすめです。
    #       https://www.ruby-toolbox.com/projects/email_validator
    #       (使い方も上記のページに載っています)
    format: { with: /\A[^@]+@[a-zA-Z0-9_.-]+\z/, message: :invalid_email_format }

  scope :matches, ->(client_search_form) {
    client_search_form.add_scopes(all)
  }

  private

  def to_utf8
    # NOTE: Kconv#toutf8(str) は半角カタカナを全角カタカナにします
    self.name = Kconv.toutf8(name) if name.present?
    self.abbr = Kconv.toutf8(abbr) if abbr.present?
    self.code = Kconv.toutf8(code) if code.present?
    self.full_name = Kconv.toutf8(full_name) if full_name.present?
    self.full_name_kana = Kconv.toutf8(full_name_kana) if full_name_kana.present?
    self.pref_name = Kconv.toutf8(pref_name) if pref_name.present?
    self.address_city = Kconv.toutf8(address_city) if address_city.present?
    self.address_extra = Kconv.toutf8(address_extra) if address_extra.present?
    self.sales_person_name = Kconv.toutf8(sales_person_name) if sales_person_name.present?
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :confirm_update, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @client_search_form = ClientSearchForm.new(client_search_form_params)
    @clients = Client.matches(@client_search_form)
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  def confirm_create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.valid?
        format.html { render }
      else
        format.html { render action: 'new' }
      end
    end
  end

  # GET /clients/1/edit
  def edit
  end

  def confirm_update
    @client.attributes = client_params

    respond_to do |format|
      if @client.valid?
        format.html { render }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: t("message.successfully_created", name: Client.model_name.human) }
        format.json { render action: 'show', status: :created, location: @client }
      else
        format.html { render action: 'new' }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    @client.attributes = client_params

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: t("message.successfully_updated", name: Client.model_name.human) }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    # NOTE: scaffold でつくられるコントローラでは destroy が使われていますが、
    #       戻り値を使わないのであれば、destroy! を使う方がより適切なので変えています。
    @client.destroy!
    respond_to do |format|
      format.html { redirect_to clients_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, :abbr, :code, :full_name, :full_name_kana, :zipcode, :pref_name, :address_city, :address_extra, :sales_person_name, :sales_person_email)
    end

    def client_search_form_params
      params.fetch(:client_search_form, {}).permit(:name, :code, :full_name_kana)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_confirm.html.haml
.col-sm-12
  .box
    .box-header.blue-background
      .title 取引先情報
    .box-content.box-padding
      .row
        .col-sm-3.item-name
          %p
            %b= Client.human_attribute_name :name
        .col-sm-9
          = @client.name
      .row
        .col-sm-3.item-name
          %p
            %b= Client.human_attribute_name :abbr
        .col-sm-9
          = @client.abbr
      .row
        .col-sm-3.item-name
          %p
            %b= Client.human_attribute_name :code
        .col-sm-9
          = @client.code
      .row
        .col-sm-3.item-name
          %p
            %b= Client.human_attribute_name :full_name
        .col-sm-9
          = @client.full_name
      .row
        .col-sm-3.item-name
          %p
            %b= Client.human_attribute_name :full_name_kana
        .col-sm-9
          = @client.full_name_kana
      .row
        .col-sm-3.item-name
          %p
            %b= Client.human_attribute_name :zipcode
        .col-sm-9
          = @client.zipcode
      .row
        .col-sm-3.item-name
          %p
            %b= Client.human_attribute_name :pref_name
        .col-sm-9
          = @client.pref_name
      .row
        .col-sm-3.item-name
          %p
            %b= Client.human_attribute_name :address_city
        .col-sm-9
          = @client.address_city
      .row
        .col-sm-3.item-name
          %p
            %b= Client.human_attribute_name :address_extra
        .col-sm-9
          = @client.address_extra
      .row
        .col-sm-3.item-name
          %p
            %b= Client.human_attribute_name :sales_person_name
        .col-sm-9
          = @client.sales_person_name
      .row
        .col-sm-3.item-name
          %p
            %b= Client.human_attribute_name :sales_person_email
        .col-sm-9
          = @client.sales_person_email

  = form_for @client, html: {class: 'form-horizontal', role: 'form'} do |f|
    - %i|name abbr code full_name full_name_kana zipcode pref_name address_city address_extra sales_person_name sales_person_email|.each do |column|
      = f.hidden_field column

    .form-actions
      .row
        .col-sm-8.col-sm-offset-3
          = f.submit '保存', class: 'btn btn-primary'
          = link_to '戻る', @client.new_record? ? new_client_path : edit_client_path, class: 'btn', onclick: "window.history.back();"

app/views/clients/_form.html.haml
= form_for @client, url: @client.new_record? ? confirm_create_clients_path : confirm_update_client_path, html: {class: 'form-horizontal', role: 'form'} do |f|
  - if @client.errors.any?
    #error_explanation.alert.alert-danger
      %ul
        - @client.errors.full_messages.each do |msg|
          %li= msg
  .box
    .box-header.blue-background
      .title 取引先情報
    .box-content.box-padding
      .form-group
        = f.label :name, class: 'control-label col-sm-3' do
          = Client.model_name.human
          %span.required_mark *
        .col-sm-8
          = f.text_field :name, class: 'form-control'

      .form-group
        = f.label :abbr, class: 'control-label col-sm-3'
        .col-sm-8
          = f.text_field :abbr, class: 'form-control'

      .form-group
        = f.label :code, class: 'control-label col-sm-3'
        .col-sm-8
          = f.text_field :code, class: 'form-control'
      
      .form-group
        = f.label :full_name, class: 'control-label col-sm-3'
        .col-sm-8
          = f.text_field :full_name, class: 'form-control'

      .form-group
        = f.label :full_name_kana, class: 'control-label col-sm-3'
        .col-sm-8
          = f.text_field :full_name_kana, class: 'form-control'

      .form-group
        = f.label :zipcode, class: 'control-label col-sm-3'
        .col-sm-8
          = f.text_field :zipcode, class: 'form-control'

      .form-group
        = f.label :pref_name, class: 'control-label col-sm-3'
        .col-sm-8
          = f.text_field :pref_name, class: 'form-control'

      .form-group
        = f.label :address_city, class: 'control-label col-sm-3'
        .col-sm-8
          = f.text_field :address_city, class: 'form-control'

      .form-group
        = f.label :address_extra, class: 'control-label col-sm-3'
        .col-sm-8
          = f.text_field :address_extra, class: 'form-control'

      .form-group
        = f.label :sales_person_name, class: 'control-label col-sm-3'
        .col-sm-8
          = f.text_field :sales_person_name, class: 'form-control'

      .form-group
        = f.label :sales_person_email, class: 'control-label col-sm-3'
        .col-sm-8
          = f.text_field :sales_person_email, class: 'form-control'

    .form-actions
      .row
        .col-sm-8.col-sm-offset-3
          = f.submit '確認', class: 'btn btn-primary'
          = link_to '戻る', clients_path, class: 'btn btn-defalut'

app/views/clients/confirm_create.html.haml
- content_for :title do
  新しい取引先を登録（確認）

- content_for :breadcrumb do
  %li
    =link_to :root do
      ホーム
  %li.separator
    %i.icon-angle-right
  %li
    =link_to clients_path do
      取引先情報
  %li.separator
    %i.icon-angle-right
  %li.active
    新しい取引先を登録（確認）

= render 'confirm'

app/views/clients/confirm_update.html.haml
- content_for :title do
  取引先を編集（確認）

- content_for :breadcrumb do
  %li
    =link_to :root do
      ホーム
  %li.separator
    %i.icon-angle-right
  %li
    =link_to clients_path do
      取引先情報
  %li.separator
    %i.icon-angle-right
  %li.active
    取引先を編集（確認）

= render 'confirm'

app/views/clients/edit.html.haml
- content_for :title do
  取引先を編集

- content_for :breadcrumb do
  %li
    =link_to :root do
      ホーム
  %li.separator
    %i.icon-angle-right
  %li
    =link_to clients_path do
      取引先情報
  %li.separator
    %i.icon-angle-right
  %li.active
    取引先を編集

.col-sm-12
  = render 'form'

app/views/clients/index.html.haml
- content_for :title do
  取引先情報

- content_for :breadcrumb do
  %li
    =link_to :root do
      ホーム
  %li.separator
    %i.icon-angle-right
  %li.active
    取引先情報

.col-sm-12
  .box
    .box-content.box-padding
      = form_for @client_search_form, url: clients_path, html: {method: :get, role: 'form'} do |f|
        .row
          .col-sm-4
            .form-group
              = f.label :name, class: 'control-label'
              = f.text_field :name, class: 'form-control'
          .col-sm-4
            .form-group
              = f.label :full_name_kana, class: 'control-label'
              = f.text_field :full_name_kana, class: 'form-control'
          .col-sm-4
            .form-group
              = f.label :code, class: 'control-label'
              = f.text_field :code, class: 'form-control'
        .row
          .col-sm-12
            = button_tag type: 'submit', class: 'btn' do
              <i class="icon-search"></i>検索

.col-sm-12
  .box
    .box-content.box-padding
      = link_to '<i class="icon-plus"></i>新しい取引先を登録'.html_safe, new_client_path, class: 'btn'

.col-sm-12
  .box
    .box-content.box-no-padding{style: 'border:none;'}
      .box.bordered-box.blue-border{style: "margin-bottom:0;"}
        .box-header.blue-background
          .title 取引先一覧
      %table.table.table-bordered
        %tr
          %th.col-sm-3= Client.human_attribute_name :name
          %th.col-sm-3= Client.human_attribute_name :full_name_kana
          %th.col-sm-2= Client.human_attribute_name :code
          %th.col-sm-1 詳細
          %th.col-sm-1 編集
          %th.col-sm-1 削除

        - @clients.each do |client|
          %tr
            %td= client.name
            %td= client.full_name_kana
            %td= client.code
            / %td= link_to '<i class="icon-large icon-file"></i>'.html_safe, client_path(client)
            %td
              =link_to client_path(client) do
                %i.icon-large.icon-file"
            %td
              = link_to edit_client_path(client) do
                %i.icon-large.icon-edit
            %td
              = link_to client, :method => :delete, :data => { :confirm => t('message.delete_confirm') } do
                %i.icon-large.icon-trash

app/views/clients/new.html.haml
- content_for :title do
  新しい取引先を登録

- content_for :breadcrumb do
  %li
    =link_to :root do
      ホーム
  %li.separator
    %i.icon-angle-right
  %li
    =link_to clients_path do
      取引先情報
  %li.separator
    %i.icon-angle-right
  %li.active
    新しい取引先を登録

.col-sm-12
  = render 'form'

app/views/clients/show.html.haml
- content_for :title do
  取引先詳細

- content_for :breadcrumb do
  %li
    =link_to :root do
      ホーム
  %li.separator
    %i.icon-angle-right
  %li
    =link_to clients_path do
      取引先
  %li.separator
    %i.icon-angle-right
  %li.active
    取引先詳細

- if notice
  .col-sm-12
    %p#notice.alert.alert-info= notice

.col-sm-12
  .box
    .box-header.blue-background
      .title 取引先情報
    .box-content.box-padding
      .row
        .col-sm-3.item-name
          %p
            %b= Client.human_attribute_name :name
        .col-sm-9
          = @client.name
      .row
        .col-sm-3.item-name
          %p
            %b= Client.human_attribute_name :abbr
        .col-sm-9
          = @client.abbr
      .row
        .col-sm-3.item-name
          %p
            %b= Client.human_attribute_name :code
        .col-sm-9
          = @client.code
      .row
        .col-sm-3.item-name
          %p
            %b= Client.human_attribute_name :full_name
        .col-sm-9
          = @client.full_name
      .row
        .col-sm-3.item-name
          %p
            %b= Client.human_attribute_name :full_name_kana
        .col-sm-9
          = @client.full_name_kana
      .row
        .col-sm-3.item-name
          %p
            %b= Client.human_attribute_name :zipcode
        .col-sm-9
          = @client.zipcode
      .row
        .col-sm-3.item-name
          %p
            %b= Client.human_attribute_name :pref_name
        .col-sm-9
          = @client.pref_name
      .row
        .col-sm-3.item-name
          %p
            %b= Client.human_attribute_name :address_city
        .col-sm-9
          = @client.address_city
      .row
        .col-sm-3.item-name
          %p
            %b= Client.human_attribute_name :address_extra
        .col-sm-9
          = @client.address_extra
      .row
        .col-sm-3.item-name
          %p
            %b= Client.human_attribute_name :sales_person_name
        .col-sm-9
          = @client.sales_person_name
      .row
        .col-sm-3.item-name
          %p
            %b= Client.human_attribute_name :sales_person_email
        .col-sm-9
          = @client.sales_person_email
      .row
        .col-sm-3.item-name
          %p
            %b= Client.human_attribute_name :created_at
        .col-sm-9
          = l @client.created_at
      .row
        .col-sm-3.item-name
          %p
            %b= Client.human_attribute_name :updated_at
        .col-sm-9
          = l @client.updated_at

.col-sm-12
  .form-actions
    .row
      .col-sm-8.col-sm-offset-2
        = link_to '編集', edit_client_path(@client), class: 'btn btn-primary'
        = link_to '戻る', clients_path, class: 'btn'