config/routes.rb
Oksales::Application.routes.draw do
  resources :units

  root 'home#index'

  resources :clients do
    member do
      patch :confirm_update
    end

    collection do
      post :confirm_create
    end
  end

  resources :products do
    member do
      patch :confirm_update
    end

    collection do
      post :confirm_create
    end
  end

  resources :supplires do
    member do
      patch :confirm_update
    end

    collection do
      post :confirm_create
    end
  end

end

app/models/product.rb
require 'kconv'

class Product < ActiveRecord::Base
	before_validation :to_utf8

  validates :code, presence: true, length: { maximum: 5 }
  validates :name, presence: true, length: { maximum: 255 }
  validates :kana, length: { maximum: 255 }

  scope :matches, ->(product_search_form) {
    product_search_form.add_scopes(all)
  }

  private

  def to_utf8
    # NOTE: Kconv#toutf8(str) は半角カタカナを全角カタカナにします
    self.code = Kconv.toutf8(code) if code.present?
    self.name = Kconv.toutf8(name) if name.present?
    self.kana = Kconv.toutf8(kana) if kana.present?
    self.district= Kconv.toutf8(district) if district.present?
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :confirm_update, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @product_search_form = ProductSearchForm.new(product_search_form_params)
    @products = Product.matches(@product_search_form)
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  def confirm_create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.valid?
        format.html { render }
      else
        format.html { render action: 'new' }
      end
    end
  end

  # GET /products/1/edit
  def edit
  end

  def confirm_update
    @product.attributes = product_params

    respond_to do |format|
      if @product.valid?
        format.html { render }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: t("message.successfully_created", name: Product.model_name.human) }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    @product.attributes = product_params

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: t("message.successfully_updated", name: Product.model_name.human) }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    # NOTE: scaffold でつくられるコントローラでは destroy が使われていますが、
    #       戻り値を使わないのであれば、destroy! を使う方がより適切なので変えています。
    @product.destroy!
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:code, :name, :short_name, :kana, :product_group_id, :price, :cost_price, :tax_type, :tax_class_id, :district, :supplire_id, :unit_id, :qty_per_box, :price_type, :item_of_matrixlist, :valid_from, :valid_until, :create_user_id, :update_user_id)
    end

    def product_search_form_params
      params.fetch(:product_search_form, {}).permit(:code, :name, :kana)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_confirm.html.haml
.col-sm-12
  .box
    .box-header.blue-background
      .title 商品情報
    .box-content.box-padding
      .row
        .col-sm-3.item-name
          %p
            %b= Product.human_attribute_name :code
        .col-sm-9
          = @product.code
      .row
        .col-sm-3.item-name
          %p
            %b= Product.human_attribute_name :name
        .col-sm-9
          = @product.name
      .row
        .col-sm-3.item-name
          %p
            %b= Product.human_attribute_name :short_name
        .col-sm-9
          = @product.short_name
      .row
        .col-sm-3.item-name
          %p
            %b= Product.human_attribute_name :kana
        .col-sm-9
          = @product.kana
      .row
        .col-sm-3.item-name
          %p
            %b= Product.human_attribute_name :product_group_id
        .col-sm-9
          = @product.product_group_id
      .row
        .col-sm-3.item-name
          %p
            %b= Product.human_attribute_name :price
        .col-sm-9
          = @product.price
      .row
        .col-sm-3.item-name
          %p
            %b= Product.human_attribute_name :cost_price
        .col-sm-9
          = @product.cost_price
      .row
        .col-sm-3.item-name
          %p
            %b= Product.human_attribute_name :tax_type
        .col-sm-9
          = @product.tax_type
      .row
        .col-sm-3.item-name
          %p
            %b= Product.human_attribute_name :tax_class_id
        .col-sm-9
          = @product.tax_class_id
      .row
        .col-sm-3.item-name
          %p
            %b= Product.human_attribute_name :district
        .col-sm-9
          = @product.district
      .row
        .col-sm-3.item-name
          %p
            %b= Product.human_attribute_name :supplire_id
        .col-sm-9
          = @product.supplire_id
      .row
        .col-sm-3.item-name
          %p
            %b= Product.human_attribute_name :unit_id
        .col-sm-9
          = @product.unit_id
      .row
        .col-sm-3.item-name
          %p
            %b= Product.human_attribute_name :qty_per_box
        .col-sm-9
          = @product.qty_per_box
      .row
        .col-sm-3.item-name
          %p
            %b= Product.human_attribute_name :price_type
        .col-sm-9
          = @product.price_type
      .row
        .col-sm-3.item-name
          %p
            %b= Product.human_attribute_name :item_of_matrixlist
        .col-sm-9
          = @product.item_of_matrixlist
      .row
        .col-sm-3.item-name
          %p
            %b= Product.human_attribute_name :valid_from
        .col-sm-9
          = @product.valid_from
      .row
        .col-sm-3.item-name
          %p
            %b= Product.human_attribute_name :valid_until
        .col-sm-9
          = @product.valid_until

  = form_for @product, html: {class: 'form-horizontal', role: 'form'} do |f|
    - %i|code name short_name kana product_group_id price cost_price tax_type tax_class_id district  unit_id qty_per_box price_type item_of_matrixlist valid_from valid_until|.each do |column|
      = f.hidden_field column

    .form-actions
      .row
        .col-sm-8.col-sm-offset-3
          = f.submit '保存', class: 'btn btn-primary'
          = link_to '戻る', @product.new_record? ? new_product_path : edit_product_path, class: 'btn', onclick: "window.history.back();"

app/views/products/_form.html.haml
= form_for @product, url: @product.new_record? ? confirm_create_products_path : confirm_update_product_path, html: {class: 'form-horizontal', role: 'form'} do |f|
  - if @product.errors.any?
    #error_explanation.alert.alert-danger
      %ul
        - @product.errors.full_messages.each do |msg|
          %li= msg
  .box
    .box-header.blue-background
      .title 商品情報
    .box-content.box-padding
      .form-group
        = f.label :code, class: 'control-label col-sm-3' do
          = Product.human_attribute_name :code
          %span.required_mark *
        .col-sm-8
          = f.text_field :code, class: 'form-control'
      
      .form-group
        = f.label :name, class: 'control-label col-sm-3' do
          = Product.human_attribute_name :name
          %span.required_mark *
        .col-sm-8
          = f.text_field :name, class: 'form-control'

      .form-group
        = f.label :short_name, class: 'control-label col-sm-3'
        .col-sm-8
          = f.text_field :short_name, class: 'form-control'

      .form-group
        = f.label :kana, class: 'control-label col-sm-3'
        .col-sm-8
          = f.text_field :kana, class: 'form-control'

      .form-group
        = f.label :product_group_id, class: 'control-label col-sm-3'
        .col-sm-8
          = f.text_field :product_group_id, class: 'form-control'

      .form-group
        = f.label :price, class: 'control-label col-sm-3'
        .col-sm-8
          = f.text_field :price, class: 'form-control'

      .form-group
        = f.label :cost_price, class: 'control-label col-sm-3'
        .col-sm-8
          = f.text_field :cost_price, class: 'form-control'

      .form-group
        = f.label :tax_type, class: 'control-label col-sm-3'
        .col-sm-8
          = f.text_field :tax_type, class: 'form-control'

      .form-group
        = f.label :tax_class_id, class: 'control-label col-sm-3'
        .col-sm-8
          = f.text_field :tax_class_id, class: 'form-control'

      .form-group
        = f.label :district, class: 'control-label col-sm-3'
        .col-sm-8
          = f.text_field :district, class: 'form-control'

      .form-group
        = f.label :supplire_id, class: 'control-label col-sm-3'
        .col-sm-8
          = f.text_field :supplire_id, class: 'form-control'

      .form-group
        = f.label :unit_id, class: 'control-label col-sm-3'
        .col-sm-8
          = f.text_field :unit_id, class: 'form-control'

      .form-group
        = f.label :qty_per_box, class: 'control-label col-sm-3'
        .col-sm-8
          = f.text_field :qty_per_box, class: 'form-control'

      .form-group
        = f.label :price_type, class: 'control-label col-sm-3'
        .col-sm-8
          = f.text_field :price_type, class: 'form-control'

      .form-group
        = f.label :item_of_matrixlist, class: 'control-label col-sm-3'
        .col-sm-8
          = f.text_field :item_of_matrixlist, class: 'form-control'

      .form-group
        = f.label :valid_from, class: 'control-label col-sm-3'
        .col-sm-8
          = f.date_select:valid_from, class: 'form-control'
          
      .form-group
        = f.label :valid_until, class: 'control-label col-sm-3'
        .col-sm-8
          = f.date_select :valid_until, class: 'form-control'

    .form-actions
      .row
        .col-sm-8.col-sm-offset-3
          = f.submit '確認', class: 'btn btn-primary'
          = link_to '戻る', products_path, class: 'btn btn-defalut'

app/views/products/confirm_create.html.haml
- content_for :title do
  新しい商品を登録（確認）

- content_for :breadcrumb do
  %li
    =link_to :root do
      ホーム
  %li.separator
    %i.icon-angle-right
  %li
    =link_to products_path do
      商品情報
  %li.separator
    %i.icon-angle-right
  %li.active
    新しい商品を登録（確認）

= render 'confirm'

app/views/products/confirm_update.html.haml
- content_for :title do
  商品を編集（確認）

- content_for :breadcrumb do
  %li
    =link_to :root do
      ホーム
  %li.separator
    %i.icon-angle-right
  %li
    =link_to products_path do
      商品情報
  %li.separator
    %i.icon-angle-right
  %li.active
    商品を編集（確認）

= render 'confirm'

app/views/products/edit.html.haml
- content_for :title do
  商品を編集

- content_for :breadcrumb do
  %li
    =link_to :root do
      ホーム
  %li.separator
    %i.icon-angle-right
  %li
    =link_to products_path do
      商品情報
  %li.separator
    %i.icon-angle-right
  %li.active
    商品を編集

.col-sm-12
  = render 'form'

app/views/products/index.html.haml
- content_for :title do
  商品情報

- content_for :breadcrumb do
  %li
    =link_to :root do
      ホーム
  %li.separator
    %i.icon-angle-right
  %li.active
    商品情報

.col-sm-12
  .box
    .box-content.box-padding
      = form_for @product_search_form, url: products_path, html: {method: :get, role: 'form'} do |f|
        .row
          .col-sm-2
            .form-group
              = f.label :code, class: 'control-label'
              = f.text_field :code, class: 'form-control'
          .col-sm-4
            .form-group
              = f.label :name, class: 'control-label'
              = f.text_field :name, class: 'form-control'
          .col-sm-4
            .form-group
              = f.label :kana, class: 'control-label'
              = f.text_field :kana, class: 'form-control'
        .row
          .col-sm-12
            = button_tag type: 'submit', class: 'btn' do
              <i class="icon-search"></i>検索

.col-sm-12
  .box
    .box-content.box-padding
      = link_to '<i class="icon-plus"></i>新しい商品を登録'.html_safe, new_product_path, class: 'btn'

.col-sm-12
  .box
    .box-content.box-no-padding{style: 'border:none;'}
      .box.bordered-box.blue-border{style: 'margin-bottom:0;'}
        .box-header.blue-background
          .title 商品一覧
      %table.table.table-bordered
        %tr
          %th.col-sm-1= Product.human_attribute_name :code
          %th.col-sm-3= Product.human_attribute_name :name
          %th.col-sm-1 詳細
          %th.col-sm-1 編集
          %th.col-sm-1 削除

        - @products.each do |product|
          %tr
            %td= product.code
            %td= product.name
            %td
              =link_to product_path(product) do
                %i.icon-large.icon-file"
            %td
              = link_to edit_product_path(product) do
                %i.icon-large.icon-edit
            %td
              = link_to product, :method => :delete, :data => { :confirm => t('message.delete_confirm') } do
                %i.icon-large.icon-trash

app/views/products/new.html.haml
- content_for :title do
  新しい商品を登録

- content_for :breadcrumb do
  %li
    =link_to :root do
      ホーム
  %li.separator
    %i.icon-angle-right
  %li
    =link_to products_path do
      商品情報
  %li.separator
    %i.icon-angle-right
  %li.active
    新しい商品を登録

.col-sm-12
  = render 'form'

app/views/products/show.html.haml
- content_for :title do
  商品詳細

- content_for :breadcrumb do
  %li
    =link_to :root do
      ホーム
  %li.separator
    %i.icon-angle-right
  %li
    =link_to products_path do
      商品情報
  %li.separator
    %i.icon-angle-right
  %li.active
    商品詳細

- if notice
  .col-sm-12
    %p#notice.alert.alert-info= notice

.col-sm-12
  .box
    .box-header.blue-background
      .title 商品情報
    .box-content.box-padding
      .row
        .col-sm-3.item-name
          %p
            %b= Product.human_attribute_name :code
        .col-sm-9
          = @product.code
      .row
        .col-sm-3.item-name
          %p
            %b= Product.human_attribute_name :name
        .col-sm-9
          = @product.name
      .row
        .col-sm-3.item-name
          %p
            %b= Product.human_attribute_name :short_name
        .col-sm-9
          = @product.short_name
      .row
        .col-sm-3.item-name
          %p
            %b= Product.human_attribute_name :kana
        .col-sm-9
          = @product.kana
      .row
        .col-sm-3.item-name
          %p
            %b= Product.human_attribute_name :product_group_id
        .col-sm-9
          = @product.product_group_id
      .row
        .col-sm-3.item-name
          %p
            %b= Product.human_attribute_name :price
        .col-sm-9
          = @product.price
      .row
        .col-sm-3.item-name
          %p
            %b= Product.human_attribute_name :cost_price
        .col-sm-9
          = @product.cost_price
      .row
        .col-sm-3.item-name
          %p
            %b= Product.human_attribute_name :tax_type
        .col-sm-9
          = @product.tax_type
      .row
        .col-sm-3.item-name
          %p
            %b= Product.human_attribute_name :tax_class_id
        .col-sm-9
          = @product.tax_class_id
      .row
        .col-sm-3.item-name
          %p
            %b= Product.human_attribute_name :district
        .col-sm-9
          = @product.district
      .row
        .col-sm-3.item-name
          %p
            %b= Product.human_attribute_name :supplire_id
        .col-sm-9
          = @product.supplire_id
      .row
        .col-sm-3.item-name
          %p
            %b= Product.human_attribute_name :unit_id
        .col-sm-9
          = @product.unit_id
      .row
        .col-sm-3.item-name
          %p
            %b= Product.human_attribute_name :qty_per_box
        .col-sm-9
          = @product.qty_per_box
      .row
        .col-sm-3.item-name
          %p
            %b= Product.human_attribute_name :price_type
        .col-sm-9
          = @product.price_type
      .row
        .col-sm-3.item-name
          %p
            %b= Product.human_attribute_name :item_of_matrixlist
        .col-sm-9
          = @product.item_of_matrixlist
      .row
        .col-sm-3.item-name
          %p
            %b= Product.human_attribute_name :valid_from
        .col-sm-9
          = @product.valid_from
      .row
        .col-sm-3.item-name
          %p
            %b= Product.human_attribute_name :valid_until
        .col-sm-9
          = @product.valid_until
      .row
        .col-sm-3.item-name
          %p
            %b= Product.human_attribute_name :created_at
        .col-sm-9
          = l @product.created_at
      .row
        .col-sm-3.item-name
          %p
            %b= Product.human_attribute_name :updated_at
        .col-sm-9
          = l @product.updated_at

.col-sm-12
  .form-actions
    .row
      .col-sm-8.col-sm-offset-2
        = link_to '編集', edit_product_path(@product), class: 'btn btn-primary'
        = link_to '戻る', products_path, class: 'btn'