config/routes.rb
Oksales::Application.routes.draw do
  resources :units

  root 'home#index'

  resources :clients do
    member do
      patch :confirm_update
    end

    collection do
      post :confirm_create
    end
  end

  resources :products do
    member do
      patch :confirm_update
    end

    collection do
      post :confirm_create
    end
  end

  resources :supplires do
    member do
      patch :confirm_update
    end

    collection do
      post :confirm_create
    end
  end

end

app/views/layouts/_footer.html.haml
%footer#footer
  .footer-wrapper
    .row
      .col-sm-6.text 
        = link_to '株式会社 オオクラ', 'http://ookura-v.jp/', target: "_blank"
        %span | Copyright 2014 © Ookura co.

app/views/layouts/_header.html.haml
%header
  %nav.navbar.navbar-default
    / application logo
    = link_to 'オオクラ販売管理システム', clients_path, class: 'navbar-brand'
    / main nav toggler (show/hide)
    %a.toggle-nav.btn.pull-left{href: "#"}
      %i.icon-reorder

app/views/layouts/_sidenav.html.haml
#wrapper
  #main-nav-bg
  %nav#main-nav
    .navigation
      / navigation items
      %ul.nav.nav-stacked
        %li
          = link_to :root do
            %i.icon-dashboard
            %span ホーム
        / %li.active
        %li
          = link_to clients_path do
            %i.icon-dashboard
            %span 取引先情報（サンプル）
        / single navigation item
        %li
          = link_to '#', class: 'dropdown-collapse' do
            %i.icon-dashboard
            %span マスター管理
            %i.icon-angle-down.angle-down
          %ul.nav.nav-stacked
            %li
              = link_to supplires_path do
                %i.icon-caret-right
                %span 仕入先情報
            %li
              = link_to products_path do
                %i.icon-caret-right
                %span 商品情報
        / 受注・売上
        %li
          = link_to '#', class: 'dropdown-collapse' do
            %i.icon-dashboard
            %span 受注・売上
            %i.icon-angle-down.angle-down
          %ul.nav.nav-stacked
            %li
              = link_to '#' do
                %i.icon-caret-right
                %span 受注データ取込み（仮）
            %li
              = link_to '#' do
                %i.icon-caret-right
                %span 売上データ入力（仮）
        / 請求・入金
        %li
          = link_to '#', class: 'dropdown-collapse' do
            %i.icon-dashboard
            %span 請求・入金
            %i.icon-angle-down.angle-down
          %ul.nav.nav-stacked
            %li
              = link_to '#' do
                %i.icon-caret-right
                %span 入金入力（仮）
            %li
              = link_to '#' do
                %i.icon-caret-right
                %span 請求締指示（仮）
        / 導入
        %li
          = link_to '#', class: 'dropdown-collapse' do
            %i.icon-dashboard
            %span 導入
            %i.icon-angle-down.angle-down
          %ul.nav.nav-stacked
            %li
              = link_to units_path do
                %i.icon-caret-right
                %span 単位情報
            %li
              = link_to '#' do
                %i.icon-caret-right
                %span 消費税情報
        %li
          = link_to '#' do
            %i.icon-dashboard
            %span サイドナビサンプル
        / four level dropdown
        %li
          = link_to '#', class: 'dropdown-collapse' do
            %i.icon-folder-open-alt
            %span ドロップダウンサンプル
            %i.icon-angle-down.angle-down
          %ul.nav.nav-stacked
            %li
              = link_to '#', class: 'dropdown-collapse' do
                %i.icon-caret-right
                %span レベル2
                %i.icon-angle-down.angle-down
            %li
              = link_to '#', class: 'dropdown-collapse' do
                %i.icon-caret-right
                %span レベル2
                %i.icon-angle-down.angle-down
              %ul.nav.nav-stacked
                %li
                  = link_to '#', class: 'dropdown-collapse' do
                    %i.icon-caret-right
                    %span レベル3
                    %i.icon-angle-down.angle-down
                  %ul.nav.nav-stacked
                    %li
                      = link_to '#' do
                        %i.icon-caret-right
                        %span レベル4-1
                    %li
                      = link_to '#' do
                        %i.icon-caret-right
                        %span レベル4-2

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title oksales
    = stylesheet_link_tag    "application", media: "all"
    = stylesheet_link_tag    "application-flatty-1", media: "all"
    = stylesheet_link_tag    "application-flatty-bootstrap", media: "all"
    = stylesheet_link_tag    "application-flatty-2", media: "all"
    = stylesheet_link_tag    "application-flatty-3", media: "all"
    = stylesheet_link_tag    "application-flatty-4", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body.contrast-red
    = render 'layouts/header'
    = render 'layouts/sidenav'

    %section#content
      .container
        #content-wrapper.row
          .col-xs-12
            / page header container
            .row
              .col-sm-12
                .page-header
                  / page title
                  %h1.pull-left
                    %i.icon-th
                    %span= yield :title
                  / breadcrumbs
                  .pull-right
                    %ul.breadcrumb= yield :breadcrumb
              / content of page
              = yield

        = render 'layouts/footer'

    /[if lt IE 9]
      = javascript_include_tag "ie8"